-------------------------------------------
-- Transfer method
-------------------------------------------

-------------------------------------------
-- Generated by: Database Migration
-- Developer: KeenDev team
-- Website: https://www.keendev.team
-- Github: https://github.com/keendev-team
-------------------------------------------

create or replace function <%- migration.schemaName %>.<%- databaseItemsPrefix %>transfer (
	from_account char,
	amount decimal,
	to_account char,
	code char default null,
	datetime timestamp default null,
	description varchar default null,
	meta jsonb default null)

	returns setof <%- migration.schemaName %>.<%- databaseItemsPrefix %>transaction_result
	language plpgsql
	AS $$

	DECLARE
		transaction_code char(8);
		transaction_time timestamp;

		source_transaction_result <%- migration.schemaName %>.<%- databaseItemsPrefix %>transaction_result;
		dest_transaction_result <%- migration.schemaName %>.<%- databaseItemsPrefix %>transaction_result;

	BEGIN
		
		SELECT <%- migration.schemaName %>.<%- databaseItemsPrefix %>random_string(8) INTO transaction_code;
		transaction_code = COALESCE(code, transaction_code);

		transaction_time = COALESCE(datetime, now());

		SELECT transaction_record.code, transaction_record.balance INTO source_transaction_result FROM <%- migration.schemaName %>.<%- databaseItemsPrefix %>insert_transaction(
			from_account, amount * -1, transaction_code, transaction_time, description, meta
		) as transaction_record;

		SELECT transaction_record.code, transaction_record.balance INTO dest_transaction_result FROM <%- migration.schemaName %>.<%- databaseItemsPrefix %>insert_transaction(
			to_account, amount, transaction_code, transaction_time, description, meta
		) as transaction_record;

		return next source_transaction_result;
		return next dest_transaction_result;
	end;

	$$;
