-------------------------------------------
-- Transaction table
-------------------------------------------

-------------------------------------------
-- Generated by: Database Migration
-- Developer: KeenDev team
-- Website: https://www.keendev.team
-- Github: https://github.com/keendev-team
-------------------------------------------

-- Schema
CREATE SCHEMA IF NOT EXISTS <%- migration.schemaName %>;

create table <%- migration.schemaName %>.<%- databaseItemsPrefix %>transaction
(
	period int not null,
	timestamp timestamp default now(),

	code char(8) not null,

	account_number char(34) not null,

	amount decimal not null,
	CONSTRAINT non_zero_amount CHECK (amount <> 0),

	balance decimal not null,

	description varchar(255),
	meta jsonb
	
) PARTITION BY LIST(period);

comment on table <%- migration.schemaName %>.<%- databaseItemsPrefix %>transaction is 'List of transactions';

comment on column <%- migration.schemaName %>.<%- databaseItemsPrefix %>transaction.period is 'Payment period (e.g. 202003 or 202004)';
comment on column <%- migration.schemaName %>.<%- databaseItemsPrefix %>transaction.timestamp is 'Time that transaction has taken place';

comment on column <%- migration.schemaName %>.<%- databaseItemsPrefix %>transaction.code is 'Transaction ID';

comment on column <%- migration.schemaName %>.<%- databaseItemsPrefix %>transaction.account_number is 'Account number you''re going to add transaction to';

comment on column <%- migration.schemaName %>.<%- databaseItemsPrefix %>transaction.amount is 'Transaction amount';
comment on column <%- migration.schemaName %>.<%- databaseItemsPrefix %>transaction.balance is 'Account balance';

comment on column <%- migration.schemaName %>.<%- databaseItemsPrefix %>transaction.description is 'Human-friendly transaction description';
comment on column <%- migration.schemaName %>.<%- databaseItemsPrefix %>transaction.meta is 'Computer-friendly transaction information';
