-------------------------------------------
-- Helpers
-------------------------------------------

-------------------------------------------
-- Generated by: Database Migration
-- Developer: KeenDev team
-- Website: https://www.keendev.team
-- Github: https://github.com/keendev-team
-------------------------------------------

-- https://gist.github.com/stereoscott/ceb8e446ff1afed5968e

Create or replace function <%- migration.schemaName %>.<%- databaseItemsPrefix %>random_string (length integer)
	returns text as
	$$
	DECLARE
		chars text[] := '{0,1,2,3,4,5,6,7,8,9,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z}';
		result text := '';
		i integer := 0;
	BEGIN
		if length < 0 then
			raise exception 'Given length cannot be less than 0';
		end if;
		for i in 1..length loop
			result := result || chars[1+random()*(array_length(chars, 1)-1)];
		end loop;
		return result;
	END;
$$ language plpgsql;
